### PR TITLE
Nim support for gl only

### PR DESCRIPTION
**Pull request by johnnovak**
* Note that loader generation is not supported yet for the Nim backend

### CODE REVIEW

**Comment by Dav1dde** [comment]
That's awesome!

Just two small nitpicks, please remove the `.DS_Store` and prefix the commit with `nim:`. 

I will try to review the changes today!

**Comment by johnnovak** [comment]
Ah sorry, missed the .DS_Store... I'll fix it shortly!

**Comment by johnnovak** [comment]
Done!

**Comment by Dav1dde** [comment]
Thank you!

**Pull request merged**
