### PR TITLE
Add pascal support

### PR DESCRIPTION
**Pull request by dpethes**
Pascal generator for GL, based on the Nim generator. It doesn't have any library loader, as I use SDL2 as a loader so I have no use for it. 
Works with Freepascal 3.0.x on win32/64, most likely on older versions and other OSes as well.

Edit: added extension loading

### CODE REVIEW

**Comment by Dav1dde** [comment]
That's awesome! Thanks for your work!

**Comment by dpethes** [comment]
It should be pretty much on par with the Nim generator now. If you have any ideas for improvements, let me know :)

**Comment by Dav1dde** [comment]
I manually rebased this into the master branch and released it in version 0.1.22.
Also added it to the online generator.

Thank you very much for the backend!

**Comment by dpethes** [comment]
Thanks!

**Pull request closed without merging**
