### PR TITLE
Add Fortran generator to glad2

### PR DESCRIPTION
**Pull request by gadjalin**
A few months back I made [Fortran 2003 bindings for GLFW 3.4](https://github.com/AarnoldGad/glf90w), so naturally the next step was to support OpenGL.

This PR offers a new Fortran generator to glad2. It takes advantage of Fortran 2018 features related to C-interoperability.

- [ ] EGL
- [x] GL
- [ ] GLX
- [ ] Vulkan
- [ ] WGL

I have tested it with GL 3.3 core and compatibility profiles using my GLFW bindings.
It does not include its own loader function, it does not check for versions or extensions, and doesn't have aliasing support.
I will work on extending the capabilities of this generator in the near future.

Any feedback is appreciated. Really.

### CODE REVIEW

**Comment by Dav1dde** [comment]
Awesome! 

Before I take a look at the code, I'd like an opinion from you (sorry you just happen to be the first contributor here), to not derail the PR I opened a [discussion](https://github.com/Dav1dde/glad/discussions/489).

**Comment by gadjalin** [comment]
After messing a little bit the git history and following #489 , I have moved my extension to [its own repo](https://github.com/AarnoldGad/glad-fortran), taking advantage of glad2's [extension system](https://github.com/Dav1dde/glad/wiki/Extending-Glad). I will play around and test a little more my code before publishing it as a PyPI package.
I tested it locally and it works like a charm!

I can close this one.

**Comment by Dav1dde** [comment]
Awesome! I tried adding it to the web generator, but it fails to generate, du to a reference to `config['ALIAS']` when the config does not include that option [here](https://github.com/AarnoldGad/glad-fortran/blob/ca7c332a517de9dea1b67d121837a607f3a7e4ee/glad_fortran/generator/fortran/__init__.py#L523-L524).

```py
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  | Traceback (most recent call last):
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  |   File "/usr/src/app/gladweb/views/index.py", line 116, in generate
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  |     url = glad_generate()
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  |           ^^^^^^^^^^^^^^^
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  |   File "/usr/src/app/gladweb/views/index.py", line 83, in glad_generate
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  |     feature_sets = list(select(specification, api, parse_version(version)) for api, version in apis)
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  |   File "/usr/src/app/gladweb/views/index.py", line 83, in <genexpr>
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  |     feature_sets = list(select(specification, api, parse_version(version)) for api, version in apis)
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  |   File "/usr/src/app/gladweb/views/index.py", line 79, in select
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  |     return generator.select(specification, api, version, profile, filtered_extensions, config, sink=sink)
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  |   File "/opt/venv/lib/python3.11/site-packages/glad_fortran/generator/fortran/__init__.py", line 523, in select
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  |     if config['ALIAS']:
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  |        ~~~~~~^^^^^^^^^
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  |   File "/opt/venv/lib/python3.11/site-packages/glad/config.py", line 241, in __getitem__
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  |     return self._values[item]
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  |            ~~~~~~~~~~~~^^^^^^
Sep 29 10:02:27 iridium docker-compose[403009]: web_1  | KeyError: 'ALIAS'
```

**Comment by gadjalin** [comment]
Fixed!

I missed that, I originally started taking example on the rust generator, but I didn't quite get how aliasing works or what it is. Maybe you have some documentation on that, or I'll figure it out eventually when I try to implement it.

There's still a bunch of things I want to improve in general.

**Comment by Dav1dde** [comment]
Some functions used to be provided by extensions and then they got moved to core with a different name, the aliasing sets it up so if either the GPU supports the core version or the extension you can call either function name and it works. Without it you would have to check for whether the extension is available or not.

**Pull request closed without merging**
