### PR TITLE
CMake: use target_include_directories(PUBLIC)

### PR DESCRIPTION
**Pull request by ranjak**
This causes GLAD_INCLUDE_DIRS to be automatically added to the include directories of the target that glad is being linked to.

E.g I only have to type `target_link_libraries(my_target glad)`, I don't need to add `target_include_directories(my_target PRIVATE ${GLAD_INCLUDE_DIRS})`.

The "old" way still works of course, this won't break anything AFAICT.

### CODE REVIEW

**Comment by ranjak** [comment]
Updated with @rwols 's tweaks.

**Comment by Dav1dde** [comment]
Thanks for your work, I hope I find time this weekend to merge all open pull requests.

**Comment by Dav1dde** [comment]
Pushed in 337695bc80bdd7d49692b01f21246b6f5398bea2 - I might have broken it, can you check if it still works (Check the latest version: [master](https://github.com/Dav1dde/glad/blob/master/CMakeLists.txt))? Thanks!

**Comment by rwols** [comment]
I just upgraded the glad submodule in my project and it compiles fine here!

**Comment by Dav1dde** [comment]
Great, thank you!

**Pull request closed without merging**
